### PR TITLE
Add support for VALARM option.

### LINKED ISSUE #46: Add VALARM option
Hello all!

For my project, I need to specify alarms/notifications for an .ical file I'm building. But there are no hooks or method I can return the Alarm object like I can return Items/Events. Am I missing something, how can I get around this. Are you planning to add a VALARM option in the future?

Best regards

### PR DESCRIPTION
**Pull request by malteger**
Add the possibility to add VALARM subcomponents to calendar entries.

The VALARM component must be constructed directly using the `icalendar.Alarm` class, this is just a minimal wrapper to be able to add it to events.

Closes #46

### CODE REVIEW

**Comment by malteger** [comment]
This should work in theory and I welcome any comments on the implementation as sub components where not supported prior to this.

I will add it to a project of mine and see if the calendar entries are working correctly.

**Comment by aleksihakli** [comment]
Great stuff @malteger! Ping back once you've tested the valarms and the PR is ready for merging :)

**Comment by malteger** [comment]
Works as expected in two clients, so should be fine.

The only problem is that there is absolutely no documentation on the `Alarm` class inside of icalendar, the only example would be in the test I added...

**Comment by malteger** [comment]
I have added an example in the docs as it took me some time to figure the trigger settings out. I hope that this is not too much and out of scope for django-ical (might be better to include it in icalendars docs)

@aleksihakli Otherwise this works and is ready to be merged

**Comment by aleksihakli** [comment]
Looks good @malteger! I think having the VALARM description in docs is nice. I'll merge this and bake a new release. Thank you for the contribution :)

**Pull request merged**
