### PR TITLE
Migrate from Travis to GitHub actions

### PR DESCRIPTION
**Pull request by aleksihakli**
Travis CI has a new pricing model which places limits on open source.

* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
* https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

Many projects are moving to GitHub Actions instead, including Jazzband projects: 

* https://github.com/orgs/jazzband/projects/1
* https://github.com/jazzband-roadies/help/issues/206

This is based on https://github.com/jazzband/contextlib2/pull/26.

TODO:

* [x] @jezdez to add `JAZZBAND_RELEASE_KEY` to the repo secrets.

### CODE REVIEW

**Comment by aleksihakli** [comment]
@jezdez opened a PR for django-ical in the same run, this supposedly also needs an updated PyPI mirror key?

**Comment by jezdez** [comment]
> @jezdez opened a PR for django-ical in the same run, this supposedly also needs an updated PyPI mirror key?

Yes, could you  please use the PR text as I've used in the other Jazzband projects? E.g. https://github.com/jazzband/django-pipeline/pull/738

If you add me to the PR text it allows me track the progress better.

**Comment by jezdez** [comment]
FTR I have more time again later this week to work on those ports and will get back to you then withr reviews

**Comment by aleksihakli** [comment]
Sure thing, I'll use the full project and issue IDs in any upcoming PRs.

**Review by jezdez — APPROVED** [review]

**Pull request merged**
